export const Images = {
  Logo: require('../../assets/images/Logo/Logo.png'),
  BackGroung1: require('../../assets/images/BackGround/BgPattern_1.png'),
  BackGroung2: require('../../assets/images/BackGround/BgPattern-2.png'),
  BackGroung3: require('../../assets/images/BackGround/BgPattern_2.png'),
  Feature1: require('../../assets/images/FeatureScreen/Feature_1.png'),
  Feature2: require('../../assets/images/FeatureScreen/Feature_2.png'),
  FaceBookIcon: require('../../assets/images/SignInScreen/facebook_icon.png'),
  GoogleIcon: require('../../assets/images/SignInScreen/google-icon.png'),
  Profile: require('../../assets/images/SignUpScreen/Profile.png'),
  Password: require('../../assets/images/SignUpScreen/Password.png'),
  Email_1: require('../../assets/images/SignUpScreen/Email.png'),
  Back: require('../../assets/images/CommonImage/Back_Icon.png'),
  Dot: require('../../assets/images/ForgotPassScreen/Dot.png'),
  Email: require('../../assets/images/ForgotPassScreen/Email.png'),
  Message_2: require('../../assets/images/ForgotPassScreen/Message.png'),
  Success_Tick_Icon: require('../../assets/images/SuccessScreen/Success_Tick_Icon.png'),
  PayPal: require('../../assets/images/PaymentMethodScreen/PayPal.png'),
  Visa: require('../../assets/images/PaymentMethodScreen/Visa.png'),
  Payonner: require('../../assets/images/PaymentMethodScreen/Payoneer.png'),
  Gallery: require('../../assets/images/UploadPhotoScreen/Gallery.png'),
  Camera: require('../../assets/images/UploadPhotoScreen/Camera.png'),
  Profile_Img: require('../../assets/images/UploadPreviewScreen/Profile_Img.png'),
  Close_Icon: require('../../assets/images/UploadPreviewScreen/Close_Icon.png'),
  Map_Pin_Img: require('../../assets/images/SetLocationScreen/Map_Pin_Img.png'),
  Notification: require('../../assets/images/HomeScreen/Icon_Notifiaction.png'),
  Search_Icon: require('../../assets/images/HomeScreen/Search_Icon.png'),
  Filter: require('../../assets/images/HomeScreen/Filter_Icon.png'),
  Ads: require('../../assets/images/HomeScreen/Ads_Image.png'),
  Home_Menu: require('../../assets/images/BottomBar_Menu/Home.png'),
  Profile_Menu: require('../../assets/images/BottomBar_Menu/Profile.png'),
  Shop_Menu: require('../../assets/images/BottomBar_Menu/Shop.png'),
  Chat_Menu: require('../../assets/images/BottomBar_Menu/Chat.png'),
  Call: require('../../assets/images/ChattingScreen/Call_Icon.png'),
  Send: require('../../assets/images/ChattingScreen/Send_Icon.png'),

  Restaurant_1: require('../../assets/images/Restaurant/Restaurant_1.png'),
  Restaurant_2: require('../../assets/images/Restaurant/Restaurant_2.png'),
  Restaurant_3: require('../../assets/images/Restaurant/Restaurant_3.png'),
  Restaurant_4: require('../../assets/images/Restaurant/Restaurant_4.png'),
  Restaurant_5: require('../../assets/images/Restaurant/Restaurant_5.png'),
  Restaurant_6: require('../../assets/images/Restaurant/Restaurant_6.png'),

  menu_1: require('../../assets/images/Popular_Menu/Menu_1.png'),
  menu_2: require('../../assets/images/Popular_Menu/Menu_2.png'),
  menu_3: require('../../assets/images/Popular_Menu/Menu_3.png'),
  menu_4: require('../../assets/images/Popular_Menu/Menu_4.png'),
  menu_5: require('../../assets/images/Popular_Menu/Menu_5.png'),
  menu_6: require('../../assets/images/Popular_Menu/Menu_6.png'),
  menu_7: require('../../assets/images/Popular_Menu/Menu_7.png'),
  menu_8: require('../../assets/images/Popular_Menu/Menu_8.png'),

  Blur_Star: require('../../assets/images/RattingScreen/Blur_Star.png'),
  Fill_Star: require('../../assets/images/RattingScreen/Fill_Star.png'),
  Edit_Icon: require('../../assets/images/RattingScreen/Edit_Icon.png'),

  voucher_2: require('../../assets/images/VoucherScreen/Voucher_2.png'),
  voucher_3: require('../../assets/images/VoucherScreen/Voucher_3.png'),

  Checked_Icon: require('../../assets/images/NotificationScreen/Checked_Icon.png'),
  Cross_Icon: require('../../assets/images/NotificationScreen/Cross_Icon.png'),
  Money_Icon: require('../../assets/images/NotificationScreen/Money_Icon.png'),

  Call_End_Icon: require('../../assets/images/CallScreen/Close_Icon.png'),
  Speaker_Icon: require('../../assets/images/CallScreen/Speaker_Icon.png'),
  Minus_Icon: require('../../assets/images/OrderDetailsScreen/Minus_Icon.png'),
  Plus_Icon: require('../../assets/images/OrderDetailsScreen/Plus_Icon.png'),

  Edit_Pencil_Icon: require('../../assets/images/ProfileScreen/Edit_Icon.png'),
  Voucher_Icon: require('../../assets/images/ProfileScreen/Voucher_Icon.png'),

  Track_Marker: require('../../assets/images/TrakOrderScreen/Track_Marker.png'),
  Call_Icon: require('../../assets/images/TrakOrderScreen/Call_Icon.png'),
  Clock_Icon: require('../../assets/images/TrakOrderScreen/Clock_Icon.png'),
  Delivery_Men_Photo: require('../../assets/images/TrakOrderScreen/Delivery_Men_Photo.png'),
  Message_Icon: require('../../assets/images/TrakOrderScreen/Message_Icon.png'),
  Direction_Icon: require('../../assets/images/TrakOrderScreen/Direction_Icon.png'),

  Fav_Icon: require('../../assets/images/DetailsRestaurantScreen/Fav_Icon.png'),
  MapPin_Icon: require('../../assets/images/DetailsRestaurantScreen/MapPin_Icon.png'),
  Location_Icon: require('../../assets/images/DetailsRestaurantScreen/Location_Icon.png'),
  Restaurant_Photo: require('../../assets/images/DetailsRestaurantScreen/Restaurant_Photo.png'),
  Star_Icon: require('../../assets/images/DetailsRestaurantScreen/Star_Icon.png'),

  ShoppingBag: require('../../assets/images/DetailsMenuScreen/ShoppingBag.png'),
};
